HELP = False
INPORB_NAME = None
CLEAN = False
NMOS = None
H5 = None
H5_UPDATE = True
SYM = True
FIND_NBAS= True
NBAS_ARRAY = None
PRIM = True
NAME = 'm2m'
RECURSIVE_MODE = False
INPORB_SET = None
CALC_DENSITY = False
SET_ENERGY_TO_OCC = False
ENERGIES_FROM_HD5 = False
SYM_LABELS = True
KEEP_HDF5 = False
